app:
  directory: '~/Library/Application Support/hister'
  log_level: 'error'
  color_scheme: 'automatic'
  search_url: 'https://duckduckgo.com/?q={query}'   # fallback when no local hit

server:
  address: '127.0.0.1:4433'
  database: 'db.sqlite3'
